[programs.localnet]
solana_dms = "F5ZaCxEgNuiR5buHmRChHAcChVvMzAHR9nqS5JFyDhEM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
sidtest = "echo 'yes'"

# `anchor test` = `solana-test-validator -> anchor build -> anchor deploy -> anchor run test -> kill solana-test-validator`
# `anchor localnet` = `solana-test-validator -> anchor build -> anchor deploy` - leaves ledger up, useful for client dev